const jobsData = [
  {
    id: 1,
    title: "Senior Software Engineer - Copilot Web Development",
    location: "Beijing, China",
    workType: "hybrid",
    datePosted: "Nov 27, 2024",
    profession: "software engineering",
    employmentType: "full-time",
    experience: "senior level",
    travel: "0-25%",
    description: `We are inviting you to join the Copilot Team, where we are redefining the future of AI-powered experiences. 
      The Copilot Team is at the forefront of innovation, building intelligent solutions that empower users across devices.`,
    qualifications: [
      "Bachelor's/Master's degree in computer science.",
      "7+ years of Web UI development experience.",
      "Experience in JavaScript, React, and RESTful APIs.",
    ],
  },
  {
    id: 2,
    title:
      "Digital Solution Sales Specialist, Irish Market, Azure Infrastructure",
    location: "Dublin, Ireland",
    workType: "hybrid",
    datePosted: "Nov 27, 2024",
    profession: "sales",
    employmentType: "full-time",
    experience: "mid level",
    travel: "0-10%",
    description: `In Small, Medium, Corporate (SMC) and Digital Sales, we have set out with the purpose of empowering our customers 
      through the unique value of the Microsoft cloud.`,
    qualifications: [
      "Experience in sales and a proven track record.",
      "Knowledge of cloud technologies, preferably Azure.",
      "Strong communication and organizational skills.",
    ],
  },
  {
    id: 3,
    title: "Product Manager - AI Solutions",
    location: "San Francisco, USA",
    workType: "remote",
    datePosted: "Nov 15, 2024",
    profession: "product management",
    employmentType: "full-time",
    experience: "mid level",
    travel: "0-10%",
    description: `We are looking for a Product Manager to join our AI Solutions team, where you will help shape the future of AI-driven products.`,
    qualifications: [
      "3+ years of product management experience.",
      "Experience with AI or machine learning projects.",
      "Excellent communication and leadership skills.",
    ],
  },
  {
    id: 4,
    title: "UX Designer - Marketing Cloud",
    location: "London, UK",
    workType: "on-site",
    datePosted: "Nov 20, 2024",
    profession: "design",
    employmentType: "contract",
    experience: "mid level",
    travel: "0-5%",
    description: `We are looking for a UX Designer to join our Marketing Cloud team to craft seamless and beautiful user experiences.`,
    qualifications: [
      "2+ years of experience in UX design.",
      "Strong portfolio showcasing UI/UX skills.",
      "Proficiency in Figma, Sketch, and prototyping tools.",
    ],
  },
  {
    id: 5,
    title: "Junior Data Analyst - Customer Insights",
    location: "Toronto, Canada",
    workType: "remote",
    datePosted: "Nov 10, 2024",
    profession: "data analysis",
    employmentType: "full-time",
    experience: "entry level",
    travel: "0%",
    description: `Join our Customer Insights team as a Junior Data Analyst and help us analyze customer behavior to drive business insights.`,
    qualifications: [
      "Bachelor's degree in data science or related field.",
      "Experience with SQL and Excel.",
      "Strong analytical and problem-solving skills.",
    ],
  },
  {
    id: 6,
    title: "Software Engineering Manager - Cloud Security",
    location: "Seattle, USA",
    workType: "hybrid",
    datePosted: "Nov 28, 2024",
    profession: "software engineering",
    employmentType: "full-time",
    experience: "senior level",
    travel: "0-15%",
    description: `We are seeking a Software Engineering Manager to lead our Cloud Security team and ensure we maintain top-notch security for our products.`,
    qualifications: [
      "5+ years of experience managing software engineering teams.",
      "Expertise in cloud technologies, preferably Azure.",
      "Strong technical background in security solutions.",
    ],
  },
  {
    id: 7,
    title: "Customer Support Specialist - SaaS Products",
    location: "Berlin, Germany",
    workType: "on-site",
    datePosted: "Nov 18, 2024",
    profession: "customer support",
    employmentType: "part-time",
    experience: "entry level",
    travel: "0%",
    description: `We are looking for a Customer Support Specialist to assist our customers with our SaaS products, ensuring high-quality service and satisfaction.`,
    qualifications: [
      "Experience in customer support, preferably with SaaS products.",
      "Strong communication skills.",
      "Proficiency in both German and English languages.",
    ],
  },
  {
    id: 8,
    title: "Marketing Specialist - Content Strategy",
    location: "Sydney, Australia",
    workType: "remote",
    datePosted: "Nov 22, 2024",
    profession: "marketing",
    employmentType: "full-time",
    experience: "mid level",
    travel: "0-10%",
    description: `As a Marketing Specialist, you will develop content strategies to enhance our digital footprint and engagement.`,
    qualifications: [
      "3+ years of experience in content marketing.",
      "Strong writing and editing skills.",
      "Experience with digital marketing tools and analytics.",
    ],
  },
  {
    id: 9,
    title: "Human Resources Generalist",
    location: "New York, USA",
    workType: "on-site",
    datePosted: "Nov 12, 2024",
    profession: "human resources",
    employmentType: "full-time",
    experience: "mid level",
    travel: "0-5%",
    description: `We are seeking an HR Generalist to support our HR operations, including recruitment, onboarding, and employee relations.`,
    qualifications: [
      "Bachelor's degree in human resources or related field.",
      "2+ years of HR experience.",
      "Strong interpersonal and communication skills.",
    ],
  },
  {
    id: 10,
    title: "Cloud Infrastructure Engineer",
    location: "Mumbai, India",
    workType: "hybrid",
    datePosted: "Nov 17, 2024",
    profession: "software engineering",
    employmentType: "full-time",
    experience: "mid level",
    travel: "0-15%",
    description: `Join our Cloud team to work on scalable cloud infrastructure and ensure high availability and reliability.`,
    qualifications: [
      "3+ years of experience with cloud platforms (AWS/Azure).",
      "Strong background in Linux and scripting languages.",
      "Experience in infrastructure as code tools such as Terraform.",
    ],
  },
  {
    id: 11,
    title: "Full Stack Developer",
    location: "Paris, France",
    workType: "hybrid",
    datePosted: "Nov 29, 2024",
    profession: "software engineering",
    employmentType: "full-time",
    experience: "mid level",
    travel: "0-10%",
    description: `We are looking for a Full Stack Developer to join our growing engineering team to build robust and scalable web applications.`,
    qualifications: [
      "4+ years of full stack development experience.",
      "Experience with JavaScript frameworks such as React and Node.js.",
      "Familiarity with databases like MongoDB or SQL.",
    ],
  },
  {
    id: 12,
    title: "Content Writer",
    location: "Cape Town, South Africa",
    workType: "remote",
    datePosted: "Dec 1, 2024",
    profession: "marketing",
    employmentType: "part-time",
    experience: "entry level",
    travel: "0%",
    description: `We are seeking a creative Content Writer to develop engaging content for our blogs and social media channels.`,
    qualifications: [
      "Excellent writing skills.",
      "Experience in digital marketing content creation.",
      "Strong research skills.",
    ],
  },
];

export default jobsData;
